parameters:
services:
    validator.parabol.entity_min_number:
        class: Parabol\BaseBundle\Validator\Constraints\EntityMinNumberValidator
        arguments:
            - "@request_stack"
        tags:
            - { name: validator.constraint_validator, alias: parabol_entity_min_number } 
    parabol.utils.path:
        class: Parabol\BaseBundle\Util\PathUtil
        public: true
        arguments:
            - "@service_container"    