<?php

namespace Parabol\BaseBundle\Entity\Base;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository
{
	public function getAlias()
	{
		return strtolower(preg_replace('/[A-za-z]+\\\||[a-z]+/', '',$this->_class->name));
	}

	public function findAllEnabledWithoutProperty($property)
	{
		$alias = $this->getAlias();

		$q = $this->createQueryBuilder($alias);

		if($property && $property->getId())
		{
			foreach($this->_class->getIdentifier() as $identifier)
			{
				$q->andWhere($alias.'.'.$identifier . ' != ' . $property->__get($identifier ));
			}
		}

		return $q;
	}
}
